import localFont from "next/font/local";
import "./globals.css";
import "@usecapsule/react-sdk/styles.css";
import AuthWithWagmi from "@/lib/CapsuleProvider"; 
import 'react-toastify/dist/ReactToastify.css'; 
import { ToastContainer } from "react-toastify";
import 'react-quill/dist/quill.snow.css';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const unigo = localFont({
  src: "./fonts/Unigeo64.ttf",
  variable: "--font-unigo",
  weight: "100 500 600 700 900",
});

const bebas = localFont({
  src: "./fonts/babon.woff2",
  variable: "--font-bebas",
  weight: "100 500 600 700 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"> 
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${unigo.variable} ${bebas.variable} antialiased`}
      > 
        <ToastContainer />
        <AuthWithWagmi>
        {children} 
        </AuthWithWagmi>
      </body>
    </html>
  );
}
